#3128561 - Hook cron api
krystalcode/drupal8-entity-sync pull request #2
Opened 2020-04-20 08:38 UTC by shabananavas

2020-04-22 08:01 UTC, krystalcode requested changes

2020-04-22 08:01 UTC, krystalcode commented on entity_sync.module
> +    $items[$item_name] = _entity_sync_create_cron_job($sync_id, $entity_info);
@shabananavas The `sync_id` is the unique identifier of the sync definition, right? For example `entity_sync.sync.user`. That should then be unique so you can use that together with the operation the job will do i.e. `$items[$sync_id . '_import_list'] = ...`.

2020-04-22 08:50 UTC, shabananavas commented on entity_sync.module
> +    $items[$item_name] = _entity_sync_create_cron_job($sync_id, $entity_info);
Yup.

2020-04-22 10:15 UTC, shabananavas commented
@krystalcode I was busy writing away the code and didn't bother to test if hook_cronapi actually works. In D8, I don't think we use hook_cronapi to declare the cron jobs: https://www.drupal.org/project/ultimate_cron/issues/2744129

2020-04-23 02:30 UTC, krystalcode commented
@shabananavas 

Looked into it, the situation seems pretty complicated; there are a couple of solutions but need a bit of an investigation. We'll do that when we have the time to do so.

For now, we'll have to define the jobs as Ultimate Cron configuration files at the application level. For example: `ultimate_cron.job.entity_sync_${SyncType}`, where `${SyncType}` the ID of the sync type.

Unfortunately, passing arguments to the job is not supported; so (for now) we'll have to define a callback at the application level e.g. `MY_MODULE_entity_sync_${SyncType}` which will call a service provided by `entity_sync` with the right arguments.

I'm closing this MR as things change drastically.

2020-04-23 02:30 UTC, closed without merging