#3143534 - Export local entity queue
krystalcode/drupal8-entity-sync pull request #31
Opened 2020-06-22 11:56 UTC by shabananavas

2020-06-23 01:06 UTC, krystalcode requested changes

2020-06-23 01:06 UTC, krystalcode commented on src/Plugin/QueueWorker/ExportLocalEntity.php
> +      $data['entity']
**CHANGE REQUEST**

We should be storing the entity ID, that should be enough, and then load the entity while processing the queue item. You can store the entity type ID as well to make it easier so you don't have to load the sync config.

* Serializing and storing the whole entity is unnecessary and in some cases it can lead to serialization errors.
* We don't need to store the state of the entity at the time of queuing. In fact, if the queue frequency is configured to be long, it can lead to sending old data to the remote.

2020-06-23 01:06 UTC, krystalcode commented on src/Plugin/QueueWorker/ExportLocalEntity.php
> +   *    labels   : export, entity
**CHANGE REQUEST**

That notification was for importing a list; I don't see it making sense for exporting an individual entity. In fact, I don't remember why this was a nice to have for the import list operation.

We can remove the Issue from here, unless you see some use of it that I don't.

2020-06-23 01:06 UTC, krystalcode commented on entity_sync.module
> +    }
**CHANGE REQUEST**

We can use the operation for easily generating the key: `$sync_queue_key = "operations.export_entity.{$op}_entities.queue";`

However, remember the discussion we had about updating on-the-fly for inserts being tricky and that we will leave handling that for later. That means that we don't support that for now and the config property value has to be `FALSE`. If not, throw an `InvalidConfigurationException`.

2020-06-23 05:31 UTC, shabananavas commented on src/Plugin/QueueWorker/ExportLocalEntity.php
> +      $data['entity']
Yeah, absolutely. I missed that one.

2020-06-23 06:52 UTC, shabananavas commented
@krsytalcode All feedback addressed.

2020-06-24 04:44 UTC, krystalcode commented
Merged on Drupal.org

2020-06-24 04:44 UTC, closed without merging